# Generated by Django 4.0.1 on 2022-01-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link_to_movie',
            field=models.TextField(blank=True),
        ),
    ]
