# Generated by Django 4.0.1 on 2022-01-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='movie',
        ),
    ]
