# Generated by Django 4.0.1 on 2022-01-17 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_rename_text_review_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created_at',)},
        ),
    ]
