# Generated by Django 4.0.1 on 2022-01-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
