# Generated by Django 4.0.1 on 2022-01-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
