# Generated by Django 4.0.1 on 2022-01-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
