# Generated by Django 4.0.1 on 2022-01-18 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0020_alter_favorites_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='favorites',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
